### ISSUE TITLE
Having issues with Vapi_python dependencies.

### ISSUE THREAD

**Issue by vihandesilva** [VapiAI/python#5]
* Vapi Python SDK version: 0.1
* Python version: 3.11
* Operating System: Windows 11

### Description

As according to instructions provided in the Readme file, I installed vapi_python using the following command: 

`pip install vapi_python`

And I executed the following code to test the connection:

```
from vapi_python import Vapi

if __name__ == "__main__":
    vapi = Vapi(api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
    vapi.start(assistant_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
```

(Please note that the key id and assistant id work and they have been anonymized)

I am getting the following error when executing this code:

`Traceback (most recent call last):
  File "E:\code\python_playground\vapi_test.py", line 1, in <module>
    from vapi_python import Vapi
ImportError: cannot import name 'Vapi' from 'vapi_python' (X:\Users\vihan\AppData\Local\Programs\Python\Python311\Lib\site-packages\vapi_python\__init__.py)`

Can someone explain me the cause of this error or an alternative to avoid it? The pip package installation of vapi_python is successful.

**Comment by hal-8999-alpha** [comment]
Same

**Comment by jmanhype** [comment]
same

**Comment by jmanhype** [comment]
> * Vapi Python SDK version: 0.1
> * Python version: 3.11
> * Operating System: Windows 11
> 
> ### Description
> As according to instructions provided in the Readme file, I installed vapi_python using the following command:
> 
> `pip install vapi_python`
> 
> And I executed the following code to test the connection:
> 
> ```
> from vapi_python import Vapi
> 
> if __name__ == "__main__":
>     vapi = Vapi(api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
>     vapi.start(assistant_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
> ```
> 
> (Please note that the key id and assistant id work and they have been anonymized)
> 
> I am getting the following error when executing this code:
> 
> `Traceback (most recent call last): File "E:\code\python_playground\vapi_test.py", line 1, in <module> from vapi_python import Vapi ImportError: cannot import name 'Vapi' from 'vapi_python' (X:\Users\vihan\AppData\Local\Programs\Python\Python311\Lib\site-packages\vapi_python\__init__.py)`
> 
> Can someone explain me the cause of this error or an alternative to avoid it? The pip package installation of vapi_python is successful.

I figured it out... its the pypi we have to install from git,,, the pypi has been delted all files are empty.!

**Comment by Reynold97** [comment]
same issue

**Comment by vihandesilva** [comment]
> I have also run into this problem and have resorted to using the API with requests and basically putting together my own internal package.

What's the endpoint to send a message to the Assistant from the User? I couldn't figure it out.

**Comment by vihandesilva** [comment]
**Update**

I'm getting an error with one of the dependencies of Vapi, now. It says that the `daily `package is not found, and I can't locate the correct `daily `package on Pypi or pip.

`File "X:\code\Chatbot\backend\app.py", line 4, in <module>
    from models import Models
  File "X:\code\Chatbot\backend\models.py", line 18, in <module>
    from vapi_python import Vapi
  File "X:\code\Chatbot\backend\venv\Lib\site-packages\vapi_python\__init__.py", line 3, in <module>
    from .vapi_python import Vapi
  File "X:\code\Chatbot\backend\venv\Lib\site-packages\vapi_python\vapi_python.py", line 3, in <module>
    from .daily_call import DailyCall
  File "X:\code\Chatbot\backend\venv\Lib\site-packages\vapi_python\daily_call.py", line 18, in <module>
    class DailyCall(daily.EventHandler):
                    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'daily' has no attribute 'EventHandler'`

**Comment by nikhilro** [comment]
hey y'all, sorry about the delay. try now: https://pypi.org/project/vapi-python

**Comment by umar-anzar** [comment]
> hey y'all, sorry about the delay. try now: https://pypi.org/project/vapi-python

This isn't working, I have tried it today.

**Comment by jordancde** [comment]
Hi there, sorry for the delay. Seems I'm unable to reproduce on my end on a fresh install.

Can you try
```
pip uninstall vapi-python
pip uninstall daily-python
pip install vapi-python
```

**Comment by namanyayg** [comment]
Same. @jordancde even your latest uninstall/reinstall doesn't work

**Comment by namanyayg** [comment]
Okay, I figured out the cause, the dependency `daily-python` *does not exist* for Windows (https://pypi.org/project/daily-python/0.7.4/#files)

Trying in WSL now

**Comment by ahmadfalcon** [comment]
@namanyayg did you find the solution?

**Comment by namanyayg** [comment]
WSL2 seems to work (WSL1 won't, don't bother trying). But it seems to have much worse latency than Vapi Web.

**Comment by nikhilro** [comment]
Confirmed with Daily. They expect to have Windows support by July.

**Comment by olup** [comment]
Same error on raspberry pi zero, how could I confirm if underlying module is responsible ?

**Comment by Abhijeet-Deve** [comment]
same error

**Comment by nikhilro** [comment]
windows is not supported: https://github.com/daily-co/daily-python/issues/7

**Comment by Rumeysakeskin** [comment]
I have solved with:

```
!sudo apt-get install portaudio19-dev
!pip install vapi-python
```

**Comment by ttamoud** [comment]
> Confirmed with Daily. They expect to have Windows support by July.

Any news on that ? Working with wsl is so limiting.

Thanks.

**Comment by nikhilro** [comment]
I believe they have started work on it, let me check the ETA

**Comment by nikhilro** [comment]
End of Oct or Mid Nov~

**Comment by metorresa** [comment]
> End of Oct or Mid Nov~

any update on this? thanks

**Comment by makerGeek** [comment]
any update on this? thanks

**Comment by DominicStewart** [comment]
Hi @makerGeek,

No update yet. It's definitely on our radar though.

**Comment by zardamhussain** [comment]
> WSL2 seems to work (WSL1 won't, don't bother trying). But it seems to have much worse latency than Vapi Web.

python is using the pyaudio which is introducing the latency, i have fixed tihis issue and created the pr. but vapi team have not reviewed it yet. 

you can check out this pr
https://github.com/VapiAI/client-sdk-python/pull/12/commits/3993527c9f51cec8716db93e57b8abf5dd896129

**Comment by rroell** [comment]
Does this mean we cannot use Python for bunch calling with Vapi?

**Comment by Alexiiiine** [comment]
@rroell no. any of these sdks are just wrappers for the API that can be interacted with in the exact same way but with just using requests, and calling their various endpoints. I have done a lot of development using the VAPI API and have never used the SDK once.
